[global]

disableWatchdogWarning = false
showWarningOnDirectExecution = true

[logger]

level = "debug"
messageFormat = "%(asctime)s %(levelname) -7s %(name)s: %(message)s"

[client]

caching = true
displayEnabled = true
showErrorDetails = true

[runner]

magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true

[server]
runOnSave = false
enableWebsocketCompression = true

[browser]

gatherUsageStats = true

[theme]
primaryColor="#ff8917"
backgroundColor="#000000"
secondaryBackgroundColor="#676769"
textColor="#ffffff"
